[package]
name = "kuma-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
fern = { workspace = true }
log = { workspace = true }
logtail = { path = "../logtail" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }

#[lints]
#workspace = true
